name: publish
on:
  workflow_dispatch:
#  release:
#    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Prepare package to publish
        run: ./gradlew publish
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #          GITHUB_ACTOR: ${{ env.USER }}

      - name: publish to maven central
        run: ./gradlew jreleaserFullRelease
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{secrets.MAVEN_PASSWORD}}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{secrets.MAVEN_USERNAME}}